ci: add basic build and test workflow for ui
tomrtk/fish-code pull request #591
Opened 2023-07-13 19:17 UTC by tomrtk

2023-07-13 19:42 UTC, MindTooth commented
Not shipping a pre-built dist folder would be nice. 👌🏻

2023-07-13 20:55 UTC, MindTooth requested changes

2023-07-13 20:55 UTC, MindTooth commented on pyproject.toml
> +extras = testing
```suggestion
```

Already declared on line 198.  Should be inherited if I understand https://tox.wiki/en/latest/user_guide.html#test-environments correctly.

2023-07-17 13:06 UTC, tomrtk commented
> Not shipping a pre-built dist folder in the source would be nice. 👌🏻

This can be a first step in the direction.

2023-07-17 13:30 UTC, MindTooth approved these changes

2023-07-17 13:30 UTC, merged